stages:
  - build
  - test 
  - deploy

build: 
  stage: build
  script:
    - npm ci
    - echo "Build completed" > build-report.log
  artifacts:
    paths:
    - build-report.log

test:
  stage: test
  script:
    - npm test
    - npm install -g nyc
    - nyc npm test
  artifacts:
    paths:
      - coverage/
    reports: 
      junit: coverage/test-results.xml

pages:
  stage: deploy
  script: 
    - mkdir .public
    - cp -r coverage/* .public/
  artifacts:
    paths:
      - .public
