language: node_js

node_js:
  - "16"

stages:
  - name: Build
  - name: Test 

jobs: 
  include:
    - stage: Build
      script:
        - npm ci
    - stage: Test
      script:
        - npm test

after_success:
  - npm install -g nyc
  - nyc npm test
  - nyc report --reporter=lcov
  - cat ./coverage/lcov-report/index.html