name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 100

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci | tee output/build-report.log

    - name: Run tests
      run: |
        npm test -- --grep "Throttle tests" || true

    - name: Generate coverage report
      run: |
        npm install -g nyc
        nyc npm test || true 
        nyc report --reporter=lcov
    
    - name: Prepare coverage directory
      run: mkdir -p output/coverage

    - name: Move coverage report
      run: mv coverage/lcov-report/* output/coverage/

    - name: Upload build report
      uses: actions/upload-artifact@v3
      with:
        name: build-report
        path: output/build-report.log
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: output/coverage
